In [11]:
# !pip install --upgrade -qq "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
# !pip install -qq matplotlib jaxmarl pettingzoo
!pip install pettingzoo
!pip install gpytorch
# exit(0) #essentially, restarts the runtime after the installation

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 76.5 MB/s eta 0:00:00


In [13]:
import numpy as np
import matplotlib.pyplot as plt
from pettingzoo.mpe import simple_v3
import gpytorch

In [10]:
env = simple_v3.env(render_mode='rgb_array', continuous_actions=False)  # "human" "rgb_array"

env.reset()
for agent in env.agent_iter():
    observation, reward, termination, truncation, info = env.last()
    print(observation)
    
    # condition GP on last obs and action

    if termination or truncation:
        action = None
    else:       
        # this is where you would insert your policy
        action = env.action_space(agent).sample() 
        print(action)

    env.step(action)
env.close()

[0.         0.         1.3798318  0.31967115]
4
[0.         0.5        1.3798318  0.31967115]
0
[0.         0.375      1.3798318  0.26967114]
2
[0.5        0.28125    1.3798318  0.23217113]
2
[0.875      0.2109375  1.3298318  0.20404615]
1
[0.15625    0.15820312 1.2423317  0.18295239]
0
[0.1171875  0.11865234 1.2267067  0.16713208]
1
[-0.41210938  0.08898926  1.214988    0.15526684]
2
[0.19091797 0.06674194 1.256199   0.14636792]
1
[-0.35681152  0.05005646  1.2371072   0.13969372]
4
[-0.26760864  0.53754234  1.2727883   0.13468808]
1
[-0.7007065   0.40315676  1.2995492   0.08093384]
4
[-0.52552986  0.80236757  1.3696198   0.04061817]
0
[-0.3941474   0.60177565  1.4221728  -0.03961859]
1
[-0.79561055  0.45133176  1.4615875  -0.09979616]
4
[-0.59670794  0.83849883  1.5411487  -0.14492933]
2
[ 0.05246907  0.6288741   1.6008195  -0.22877921]
2
[ 0.5393518   0.47165558  1.5955725  -0.29166663]
1
[-0.09548615  0.35374168  1.5416373  -0.3388322 ]
0
[-0.07161462  0.26530626  1.551186   -0.3742